### PR TITLE
[#142]  Add versions to `base` dependency 

### PR DESCRIPTION
**Pull request by Leschonander**
Like where it says [here](https://pvp.haskell.org/) I changed the base to the versions that you wanted, mainly adding the range of versions supported.

### CODE REVIEW

**Comment by vrom911** [comment]
Hey @Leschonander! Sorry for bothering you, I just wonder if you need any help with this one?

**Comment by vrom911** [comment]
@Leschonander I see no activity on the issue so far, is there any specific issue-related problem? Just want to say, that we are happy to help with explaining the issue in more details.

Also, there were some significant changes in the `summoner`, so you should probably rebase on the master before continuing working on this.

**Comment by Leschonander** [comment]
Sorry, I just got swamped with a lot of work recently. Should be able to fix it up very soon, however.

**Comment by ChShersh** [comment]
This was done in #200 so I'm closing this due to inactivity. @Leschonander but I still want to say thank you for contributing to our project! :clap:

**Pull request closed without merging**
