### PR TITLE
[#448] Add -Wnoncanonical-monad-instances

### LINKED ISSUE #448: Add -Wnoncanonical-monad-instances
since GHC 8.0

### PR DESCRIPTION
**Pull request by gdziadkiewicz**
Fixes #448

### CODE REVIEW

**Review by vrom911 — COMMENTED** [review]
Neat implementation! 👍🏼 
Could you please also update the README section on the options?

**Comment by gdziadkiewicz** [comment]
Yes, I will update README

**Comment by gdziadkiewicz** [comment]
Updated README file.

**Review by vrom911 — APPROVED** [review]
Awesome 🌟 Thanks so much 👍🏼

**Pull request merged**
