### PR TITLE
[#40] Add hpack support

### LINKED ISSUE #40: Support 'hpack'
There's a lot of hype around `hpack`. Maybe it's a good idea to add support for it in `hs-init` :)
With separate flag, I guess, `-h`. It's not busy currently as I can see...

### PR DESCRIPTION
**Pull request by adituv**
* Adds CLI flags -h, --hpack
* Adds hpack toggle to the interactive flow before build script
* Generates a package.yaml instead of a cabal file when hpack is
  enabled
Resolves #40

### CODE REVIEW

**Comment by ChShersh** [comment]
@adituv Thanks a lot for your contribution! You did really great job in implementing `hpack` support inside `summoner`. I can't imagine better `hpack` support with current code. But I won't merge this Pull Request. And below I will try to explain motivation for closing this PR. It's really hard to reject somebody's work (especially when they spend their free time to contribute to your project) and I'm doing this first time so bear with me.

Here are the reasons:
* Adding `hpack` really makes code much harder to maintain. Almost every `.cabal` feature should be also duplicated for `hpack`. This involves some code duplication and introduces unnecessary complexity. 
* Since we also don't have robust testing mechanism for generated project, we need to test everything manually. And now for every feature we need to spend  twice more time to test it manually. Since we care about our projects and their quality we can't release them without testing everything thoroughly. But we don't have many time at the moment...
* Personally I don't think that `summoner` should support `hpack`. There's tool called [`hpack-converter`](https://github.com/yamadapc/hpack-convert) which can create `package.yaml` from `.cabal` file. No need to do redundant work in `summoner` if there already exist tool which can do this.

The reason why issue is still open is because we didn't figure out best way to support `hpack` without making codebase hard to maintain. I personally want for `summoner` to be beginner friendly in terms of contribution. Maybe in some future we can add `hpack` support but I don't think it will be right now... That's why we didn't add `hpack` in our next milestone for `1.1` version:

* https://github.com/kowainik/summoner/milestone/2

We have a lot of other issues and plans and project improvements. `summoner` is far from the state where its development become really slow because there's nothing to do. A lot of things can be refactored, final structure is probably not achieved. Having `hpack` will require to do more work on every `.cabal` feature without introducing really great benefit. Imagine adding multipackage project support. This will be much harder to add if need to support both `cabal` and `hpack`. To me it looks much easier to add `hpack` after adding multipackage support.

For now I want from `summoner` to support both `cabal` and `stack` at the same time without any problems. Introducing `hpack` kinda ruins `cabal + stack = <3` theme because `hpack` somewhat replaces `cabal` and `stack` support `hpack` out of the box but `cabal-install` doesn't support `hpack`. This becomes messy very quick.

But your contribution still has value to us! You don't always write code with only purpose — deliver this code to production. Sometimes code has research value. Without seeing actual code it's hard to reason about possible drawbacks and benefits. But usually nobody wants to write code just to look at it. So thank you for helping us to understand things better!

**Comment by adituv** [comment]
It's fine that you don't want to have this in the project!  I saw that the issue was tagged with help-wanted and decided to take a look, that's all.  Could you make a note of the reasons in the issue itself though, please?

I didn't know that tool existed, and that seems useful, thanks for the pointer.

As for cabal compatibility, I could see it being fine (in my opinion at least) to include a call to the hpack executable in the build script before cabal-install is called.  But I guess it doesn't matter too much as creating a package.yaml file is pretty much a one-time thing anyway.

Thank you as always for your feedback!

**Comment by ChrisPenner** [comment]
Is there any path to still allowing a package.yaml to be generated by summoner? Perhaps simply running the cabal file through the `hpack-convert` web-service after generating the project? I can probably just make a cli alias that does this for me, but it'd be nice to have it all as part of the same tool. I'm not opposed to adding this support myself if there's a path we can agree on towards adding it 😄

**Comment by vrom911** [comment]
@ChrisPenner, it's not that easy to support another external tool in `summoner` itself. And I doubt it worth it. If you share with us the command that uses `hpack-convert` we probably can add this to the README file in the extra section if that can be helpful.
We have a lot of plans for `summoner` and the support of the `hpack` will significantly slow us down in doing that, will complicate the app so much that we won't be able to maintain and add anything else to it for a long time. Also, as I'm not using `hpack` personally would mean that I won't have any ability (and motivation) to support `summoner`. Luckily, there are already tools that are taking care of `cabal` – `hpack` stuff, so people can just install and use them, and we shouldn't take the responsibility of other tools.

**Pull request closed without merging**
